#:schema node_modules/wrangler/config-schema.json
name = "worker-turso"
main = "src/index.ts"
compatibility_date = "2024-06-05"
compatibility_flags = ["nodejs_compat"]
[triggers]
# Every minute 
crons = ["* * * * *"]

[vars]
LIBSQL_DB_URL = "libsql://socialhall-manu.turso.io"